/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppConversationsRouteImport } from './routes/_app/conversations'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AppCatalogIndexRouteImport } from './routes/_app/catalog/index'
import { Route as AppCatalogCategoriesRouteImport } from './routes/_app/catalog/categories'
import { Route as AppConversationsIndexRouteImport } from './routes/_app/conversations/index'
import { Route as AppConversationsConversationIdRouteImport } from './routes/_app/conversations/$conversationId'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsAccountRouteImport } from './routes/_app/settings/account'
import { Route as AppSettingsMessengerRouteImport } from './routes/_app/settings/messenger'
import { Route as AppCatalogProductsProductIdRouteImport } from './routes/_app/catalog/products/$productId'
import { Route as AppCatalogProductsNewRouteImport } from './routes/_app/catalog/products/new'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppConversationsRoute = AppConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AppCatalogIndexRoute = AppCatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogCategoriesRoute = AppCatalogCategoriesRouteImport.update({
  id: '/catalog/categories',
  path: '/catalog/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppConversationsIndexRoute = AppConversationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppConversationsRoute,
} as any)
const AppConversationsConversationIdRoute =
  AppConversationsConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AppConversationsRoute,
  } as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsMessengerRoute = AppSettingsMessengerRouteImport.update({
  id: '/messenger',
  path: '/messenger',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppCatalogProductsProductIdRoute =
  AppCatalogProductsProductIdRouteImport.update({
    id: '/catalog/products/$productId',
    path: '/catalog/products/$productId',
    getParentRoute: () => AppRoute,
  } as any)
const AppCatalogProductsNewRoute = AppCatalogProductsNewRouteImport.update({
  id: '/catalog/products/new',
  path: '/catalog/products/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/conversations': typeof AppConversationsRouteWithChildren
  '/settings': typeof AppSettingsRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/catalog/categories': typeof AppCatalogCategoriesRoute
  '/conversations/$conversationId': typeof AppConversationsConversationIdRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/messenger': typeof AppSettingsMessengerRoute
  '/catalog/': typeof AppCatalogIndexRoute
  '/conversations/': typeof AppConversationsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/catalog/products/$productId': typeof AppCatalogProductsProductIdRoute
  '/catalog/products/new': typeof AppCatalogProductsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/catalog/categories': typeof AppCatalogCategoriesRoute
  '/conversations/$conversationId': typeof AppConversationsConversationIdRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/messenger': typeof AppSettingsMessengerRoute
  '/catalog': typeof AppCatalogIndexRoute
  '/conversations': typeof AppConversationsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/catalog/products/$productId': typeof AppCatalogProductsProductIdRoute
  '/catalog/products/new': typeof AppCatalogProductsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/conversations': typeof AppConversationsRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_app/': typeof AppIndexRoute
  '/_app/catalog/categories': typeof AppCatalogCategoriesRoute
  '/_app/conversations/$conversationId': typeof AppConversationsConversationIdRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/messenger': typeof AppSettingsMessengerRoute
  '/_app/catalog/': typeof AppCatalogIndexRoute
  '/_app/conversations/': typeof AppConversationsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/catalog/products/$productId': typeof AppCatalogProductsProductIdRoute
  '/_app/catalog/products/new': typeof AppCatalogProductsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conversations'
    | '/settings'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/catalog/categories'
    | '/conversations/$conversationId'
    | '/settings/account'
    | '/settings/messenger'
    | '/catalog/'
    | '/conversations/'
    | '/settings/'
    | '/catalog/products/$productId'
    | '/catalog/products/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/catalog/categories'
    | '/conversations/$conversationId'
    | '/settings/account'
    | '/settings/messenger'
    | '/catalog'
    | '/conversations'
    | '/settings'
    | '/catalog/products/$productId'
    | '/catalog/products/new'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/conversations'
    | '/_app/settings'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_app/'
    | '/_app/catalog/categories'
    | '/_app/conversations/$conversationId'
    | '/_app/settings/account'
    | '/_app/settings/messenger'
    | '/_app/catalog/'
    | '/_app/conversations/'
    | '/_app/settings/'
    | '/_app/catalog/products/$productId'
    | '/_app/catalog/products/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conversations': {
      id: '/_app/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AppConversationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/catalog/': {
      id: '/_app/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof AppCatalogIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/categories': {
      id: '/_app/catalog/categories'
      path: '/catalog/categories'
      fullPath: '/catalog/categories'
      preLoaderRoute: typeof AppCatalogCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conversations/': {
      id: '/_app/conversations/'
      path: '/'
      fullPath: '/conversations/'
      preLoaderRoute: typeof AppConversationsIndexRouteImport
      parentRoute: typeof AppConversationsRoute
    }
    '/_app/conversations/$conversationId': {
      id: '/_app/conversations/$conversationId'
      path: '/$conversationId'
      fullPath: '/conversations/$conversationId'
      preLoaderRoute: typeof AppConversationsConversationIdRouteImport
      parentRoute: typeof AppConversationsRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/messenger': {
      id: '/_app/settings/messenger'
      path: '/messenger'
      fullPath: '/settings/messenger'
      preLoaderRoute: typeof AppSettingsMessengerRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/catalog/products/$productId': {
      id: '/_app/catalog/products/$productId'
      path: '/catalog/products/$productId'
      fullPath: '/catalog/products/$productId'
      preLoaderRoute: typeof AppCatalogProductsProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/products/new': {
      id: '/_app/catalog/products/new'
      path: '/catalog/products/new'
      fullPath: '/catalog/products/new'
      preLoaderRoute: typeof AppCatalogProductsNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppConversationsRouteChildren {
  AppConversationsConversationIdRoute: typeof AppConversationsConversationIdRoute
  AppConversationsIndexRoute: typeof AppConversationsIndexRoute
}

const AppConversationsRouteChildren: AppConversationsRouteChildren = {
  AppConversationsConversationIdRoute: AppConversationsConversationIdRoute,
  AppConversationsIndexRoute: AppConversationsIndexRoute,
}

const AppConversationsRouteWithChildren =
  AppConversationsRoute._addFileChildren(AppConversationsRouteChildren)

interface AppSettingsRouteChildren {
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsMessengerRoute: typeof AppSettingsMessengerRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsMessengerRoute: AppSettingsMessengerRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppConversationsRoute: typeof AppConversationsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppCatalogCategoriesRoute: typeof AppCatalogCategoriesRoute
  AppCatalogIndexRoute: typeof AppCatalogIndexRoute
  AppCatalogProductsProductIdRoute: typeof AppCatalogProductsProductIdRoute
  AppCatalogProductsNewRoute: typeof AppCatalogProductsNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConversationsRoute: AppConversationsRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppCatalogCategoriesRoute: AppCatalogCategoriesRoute,
  AppCatalogIndexRoute: AppCatalogIndexRoute,
  AppCatalogProductsProductIdRoute: AppCatalogProductsProductIdRoute,
  AppCatalogProductsNewRoute: AppCatalogProductsNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
