/**
 * Generated by kysely-codegen from the migrated database. Do not edit by hand:
 * run `pnpm --filter api db:types` after applying migrations. CI fails on drift.
 *
 * Placeholder until the first migration exists.
 */
export interface DB {}
